import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Geist_Mono } from 'next/font/google';

import './globals.css';

const gtAmerica = localFont({
	src: '../public/font.otf',
	variable: '--font-display',
});

const geistMono = Geist_Mono({
	variable: '--font-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${gtAmerica.variable} ${geistMono.variable} font-mono antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
